FEAT: Allows the client to just fire a message
takenet/iframe-message-proxy pull request #2
Opened 2019-09-17 16:47 UTC by torres792

Added a parameter on the sendMessage method that will inform the system whether or not it should maintain a promise on cache. It will allow the system to just fire messages without expecting a result as a return.

2019-09-17 18:04 UTC, ceifa commented on src/IframeMessageProxy.ts
> +  public sendMessage(payload: IMessagePayload, trackPromise: boolean = true): Promise<any> {
No need to a new parameter.
This can stay on the message payload.

2019-09-17 18:04 UTC, ceifa commented on src/IframeMessageProxy.ts
> +    if (trackPromise) {
A counter logic might be better, to prevent the user from having to pass the parameter every time they want to wait for a response (the most cases).
Suggestion:
`if (!message.fireAndForget)`

2019-09-18 00:50 UTC, ceifa approved these changes

2019-09-18 21:54 UTC, samwx requested changes

2019-09-18 21:54 UTC, samwx commented on src/IframeMessageProxy.ts
> +    if (!message.message.fireAndForget) {
Change to `payload.fireAndForget`

2019-09-19 14:38 UTC, samwx approved these changes

2019-09-19 14:40 UTC, merged

2021-09-01 20:02 UTC, UserTakeBlip commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/iframe-message-proxy/v/1.2.0)
- [GitHub release](https://github.com/takenet/iframe-message-proxy/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: